### ISSUE TITLE
TypeError: Cannot handle this data type: (1, 1, 776), |u1

### ISSUE THREAD

**Issue by rightlit** [rightlit/StackGAN-v2-rev#10]
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    algo.train()
  File "/content/StackGAN-v2-rev/code/trainer.py", line 767, in train
    count, self.image_dir, self.summary_writer)
  File "/content/StackGAN-v2-rev/code/trainer.py", line 214, in save_img_results
    sup_real_img = summary.image('real_img', real_img_set)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/summary.py", line 205, in image
    image = make_image(tensor, rescale=rescale)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/summary.py", line 243, in make_image
    image = Image.fromarray(tensor)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2682, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey)
TypeError: Cannot handle this data type: (1, 1, 776), |u1

==> 
tensorboardX == 1.1

**Comment by sabhiram6** [comment]
@rightlit did u get any solution for this issue ? if yes could u please share the solution
